# Generated by Django 4.0.3 on 2022-04-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('ccode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('ccreated_at', models.DateTimeField(auto_now_add=True)),
                ('cupdated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'adminapp_course',
            },
        ),
    ]
